// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NavigateToHandlerPubSub
{
    internal sealed partial class Vsix
    {
        public const string Id = "NavigateToHandlerPubSub.6365991b-3bc0-4a20-afe7-c3dd9b44ceea";
        public const string Name = "Navigate to Handler PubSub";
        public const string Description = @"Provides a command under the editor context menu that allows you to navigate to the pub sub pattern handlers method across the entire solution that consumes the type under the cursor as a parameter. The type can be a declaration or a publish method invocation. ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alejandro Carmona";
        public const string Tags = "";
    }
}
