// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NavigateToHandlerPubSub
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string NavigateToHandlerPubSubString = "a2c0c0a5-4083-4459-9d4b-3d8fd2fc28ba";
        public static Guid NavigateToHandlerPubSub = new Guid(NavigateToHandlerPubSubString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int ShowHandlersCommand = 0x0100;
    }
}